compatibility_date = "2022-05-20"
kv_namespaces = [
  {binding = "FARMS", id = "043c324a197d4ad09223777189c57eb7", preview_id = "95860eae19cb420a8061758edd7f0136"},
]
main = "src/index.ts"
name = "farms-dev"
node_compat = true
[vars]
FORCE_UPDATE_KEY = "force"
KV_CACHE = false
[triggers]
crons = []

[env.production]
kv_namespaces = [
  {binding = "FARMS", id = "043c324a197d4ad09223777189c57eb7"},
]
name = "farms"
node_compat = true
[env.production.vars]
KV_CACHE = true
[env.production.triggers]
crons = ["0 0 * * *", "*/1 * * * *"]

# The necessary secrets are:
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
